apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "travis-build.fullname" . }}
data:
  DEBUG: "{{ .Values.debug }}"
  TRAVIS_ENABLE_DEBUG_TOOLS: "{{ .Values.enableDebugTools }}"

  PUMA_MAX_THREADS: 5
  PUMA_MIN_THREADS: 5
  PUMA_WORKERS: 8

  ROLLOUT: "redirect_io"
  ROLLOUT_REDIRECT_IO_OWNERS_BLOCKLIST: "{{ .Values.ptyOwners }}"
  ROLLOUT_REDIRECT_IO_PERCENT: "100"

  TRAVIS_SITE: "{{ .Values.site }}"
  TRAVIS_APP_HOST: "{{ .Values.appHost }}"
  TRAVIS_BUILD_APP_HOST: "{{ .Values.appHost }}"
  TRAVIS_BUILD_ENABLE_INFRA_DETECTION: "true"
  TRAVIS_BUILD_NETWORK_CHECK_URLS: "http://%{app_host}/empty.txt?job_id=%{job_id}&repo=%{repo}&via=env,http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-amd64/Packages?source=travis-ci/travis-build,http://repo.mysql.com/apt/ubuntu/dists/trusty/InRelease?source=travis-ci/travis-build"

  TRAVIS_LANGUAGE_ARCHIVE_HOST: "gcs"
  TRAVIS_MAVEN_CENTRAL_MIRROR: "https://maven-central.storage-download.googleapis.com/repos/central/data/"
  TRAVIS_UPDATE_GIT: "true"
  TRAVIS_UPDATE_GLIBC: "true"
  TRAVIS_WINDOWS_LANGS: "bash,c,cpp,csharp,dart,go,haxe,julia,node_js,powershell,r,rust,script,sh,shell"

  TRACE_COMMAND: "all"
  TRACE_GIT_COMMANDS_OWNERS: ""
  TRACE_GIT_COMMANDS_SLUGS: ""

  TRAVIS_BUILD_APT_PROXY: "{{ .Values.aptProxy }}"
  TRAVIS_BUILD_APT_SAFELIST_SKIP: "{{ .Values.aptSafelistSkip }}"
  TRAVIS_BUILD_APT_MIRRORS_GCE: "http://us-east-1.ec2.archive.ubuntu.com/ubuntu/"

  TRAVIS_BUILD_APT_PACKAGE_SAFELIST_PRECISE: "https://raw.githubusercontent.com/travis-ci/apt-package-safelist/master/ubuntu-precise"
  TRAVIS_BUILD_APT_PACKAGE_SAFELIST_TRUSTY: "https://raw.githubusercontent.com/travis-ci/apt-package-safelist/master/ubuntu-trusty"
  TRAVIS_BUILD_APT_PACKAGE_SAFELIST_XENIAL: "https://raw.githubusercontent.com/travis-ci/apt-package-safelist/master/ubuntu-xenial"
  TRAVIS_BUILD_APT_PACKAGE_SAFELIST_BIONIC: "https://raw.githubusercontent.com/travis-ci/apt-package-safelist/master/ubuntu-bionic"

  TRAVIS_BUILD_APT_SOURCE_ALIAS_LIST_PRECISE: "https://raw.githubusercontent.com/travis-ci/apt-source-whitelist/master/ubuntu.json"
  TRAVIS_BUILD_APT_SOURCE_ALIAS_LIST_TRUSTY: "https://raw.githubusercontent.com/travis-ci/apt-source-whitelist/master/ubuntu.json"
  TRAVIS_BUILD_APT_SOURCE_ALIAS_LIST_XENIAL: "https://raw.githubusercontent.com/travis-ci/apt-source-whitelist/master/ubuntu.json"
  TRAVIS_BUILD_APT_SOURCE_ALIAS_LIST_BIONIC: "https://raw.githubusercontent.com/travis-ci/apt-source-whitelist/master/ubuntu.json"

  APT_GET_MIRROR_UBUNTU: "http://mirror.jmu.edu/pub/ubuntu"
  APT_GET_UPDATE_OPT_IN: "true"
  RACK_ENV: "{{ .Values.rackEnv }}"
  TRAVIS_BUILD_GPG_KEYS_URL: "https://raw.githubusercontent.com/travis-ci/apt-gpg-keys/master/gpg_keys.json"
  TRAVIS_BUILD_GIMME_FORCE_REINSTALL: "{{ .Values.gimmeForceReinstall }}"
  GITHUB_APPS_ID: "{{ .Values.githubAppsId }}"
