apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workerclusters.travisci.com
spec:
  group: travisci.com
  names:
    kind: WorkerCluster
    listKind: WorkerClusterList
    plural: workerclusters
    singular: workercluster
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
