apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "macstadium-worker.fullname" . }}
data:
  TRAVIS_WORKER_TRAVIS_SITE: "{{ .Values.site }}"
  TRAVIS_WORKER_POOL_SIZE: "{{ .Values.concurrency.poolSize }}"

  TRAVIS_WORKER_BUILD_FIX_ETC_HOSTS: "true"
  TRAVIS_WORKER_BUILD_FIX_RESOLV_CONF: "true"
  TRAVIS_WORKER_BUILD_PARANOID: "false"

  TRAVIS_WORKER_BUILD_TRACE_ENABLED: "true"
  TRAVIS_WORKER_BUILD_TRACE_S3_KEY_PREFIX: trace/
  TRAVIS_WORKER_BUILD_TRACE_S3_REGION: us-east-1

  TRAVIS_WORKER_QUEUE_TYPE: "amqp"
  TRAVIS_WORKER_QUEUE_NAME: "{{ .Values.queue }}"
  TRAVIS_WORKER_AMQP_HEARTBEAT: "60s"
  TRAVIS_WORKER_RABBITMQ_SHARDING: "true"

  TRAVIS_WORKER_INFRA: "macstadium"
  TRAVIS_WORKER_PROVIDER_NAME: "jupiterbrain"
  TRAVIS_WORKER_JUPITERBRAIN_IMAGE_SELECTOR_TYPE: "api"
  TRAVIS_WORKER_JUPITERBRAIN_SSH_KEY_PATH: "/etc/secret/travis-vm.key"

  TRAVIS_WORKER_STARTUP_TIMEOUT: "8m"
  TRAVIS_WORKER_SCRIPT_UPLOAD_TIMEOUT: "6m"

  {{- if .Values.redis.name -}}
  TRAVIS_WORKER_CONCURRENT_JOBS_REDIS_URL: "redis://{{ .Values.redis.name }}/"
  TRAVIS_WORKER_CONCURRENT_JOBS_PREFIX: {{ include "macstadium-worker.fullname" }}
  TRAVIS_WORKER_CONCURRENT_JOBS_TOTAL_FILE: /etc/worker/total-concurrent-jobs
  {{- end -}}
