language: ruby
dist: xenial
addons:
  snaps:
  - name: helm
    classic: true
    channel: 3.2/stable

before_deploy:
- ls dist
- openssl aes-256-cbc -K $encrypted_8a2a23268e29_key -iv $encrypted_8a2a23268e29_iv
  -in gcs-credentials.json.enc -out gcs-credentials.json -d

deploy:
  provider: gcs
  edge:
    branch: master
  key_file: gcs-credentials.json
  bucket: travis-ci-helm-charts
  local_dir: dist
  acl: public-read
  on:
    repo: travis-ci/kubernetes-config

after_success:
- "./shared/update-staging.sh"

branches:
  except:
  - flux-sync
  - flux-write-check
