apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imaged.fullname" . }}
  labels:
    app.kubernetes.io/name: imaged
    helm.sh/chart: {{ include "macbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imaged
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imaged
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: ansible-secrets
          secret:
            secretName: {{ include "imaged.fullname" . }}-ansible
      containers:
        - name: imaged
          image: "{{ .Values.imaged.image.repository }}:{{ .Values.imaged.image.tag }}"
          imagePullPolicy: {{ .Values.imaged.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "imaged.fullname" . }}
            - secretRef:
                name: {{ include "imaged.fullname" . }}
          volumeMounts:
            - name: ansible-secrets
              mountPath: /etc/secrets
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
