# Default values for jupiter-brain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/travis-ci-staging-services-1/jupiter-brain
  tag: v1.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Pull secrets from trvs keychain
trvs:
  # If not enabled, be sure to set secretName and create a secret with the
  # necessary environment variables for jupiter-brain
  enabled: false
  app: jupiter-brain
  env: ""
  pro: false

# Override the name of the secret with environment variables.
#
# If trvs.enabled is true, it will create a secret with this name instead
# of using the fullname of the deployment.
#
# If trvs.enabled is false, this should be set and you must create a secret
# with the given name that has the right environment variables.
secretName: ""

concurrency:
  create: 20
  delete: 20

requestTimeout: 5m

honeycomb:
  dataset: ""
  sampleRate: 1

service:
  type: ClusterIP
  port: 80

imagePullSecrets: gcr-io  

