---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-common
data:
  TRAVIS_WORKER_AMQP_HEARTBEAT: "60s"
  TRAVIS_WORKER_BUILD_FIX_ETC_HOSTS: "true"
  TRAVIS_WORKER_BUILD_FIX_RESOLV_CONF: "true"
  TRAVIS_WORKER_BUILD_PARANOID: "false"
  TRAVIS_WORKER_BUILD_TRACE_ENABLED: "true"
  TRAVIS_WORKER_BUILD_TRACE_S3_KEY_PREFIX: trace/
  TRAVIS_WORKER_BUILD_TRACE_S3_REGION: us-east-1
  TRAVIS_WORKER_INFRA: "macstadium"
  TRAVIS_WORKER_QUEUE_TYPE: "amqp"
  TRAVIS_WORKER_QUEUE_NAME: "builds.macstadium6"
  TRAVIS_WORKER_PROVIDER_NAME: "jupiterbrain"
  TRAVIS_WORKER_JUPITERBRAIN_IMAGE_SELECTOR_TYPE: "api"
  TRAVIS_WORKER_JUPITERBRAIN_SSH_KEY_PATH: "/etc/secret/travis-vm-ssh-key"
  TRAVIS_WORKER_STARTUP_TIMEOUT: "8m"
  TRAVIS_WORKER_SCRIPT_UPLOAD_TIMEOUT: "6m"
  TRAVIS_WORKER_RABBITMQ_SHARDING: "true"
