# Default values for travis-vcs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay:io/travisci/travis-vcs
  tag: ''
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Pull secrets from trvs keychain
trvs:
  # If not enabled, be sure to set secretName and create a secret with the
  # necessary environment variables for travis-vcs
  enabled: false
  app: "travis-vcs"
  env: ""
  pro: false
