apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gce-worker.fullname" . }}
data:
  TRAVIS_WORKER_AMQP_HEARTBEAT: "60s"
  TRAVIS_WORKER_BUILD_FIX_ETC_HOSTS: "true"
  TRAVIS_WORKER_BUILD_FIX_RESOLV_CONF: "true"
  TRAVIS_WORKER_BUILD_PARANOID: "false"
  TRAVIS_WORKER_BUILD_TRACE_ENABLED: "true"
  TRAVIS_WORKER_BUILD_TRACE_S3_KEY_PREFIX: trace/
  TRAVIS_WORKER_BUILD_TRACE_S3_REGION: us-east-1
  TRAVIS_WORKER_HARD_TIMEOUT: "120m"
  TRAVIS_WORKER_POOL_SIZE: "5"
  TRAVIS_WORKER_POOL_SIZE: "{{ .Values.poolSize }}"
  TRAVIS_WORKER_QUEUE_TYPE: "amqp"
  TRAVIS_WORKER_RABBITMQ_SHARDING: "true"
  TRAVIS_WORKER_SCRIPT_UPLOAD_TIMEOUT: "6m"
  TRAVIS_WORKER_STARTUP_TIMEOUT: "8m"
  TRAVIS_WORKER_TRAVIS_SITE: "{{ .Values.site }}"
  {{ if .Values.queue -}}
  TRAVIS_WORKER_QUEUE_NAME: "{{ .Values.queue }}"
  {{- end }}

  TRAVIS_WORKER_INFRA: "gce"
  TRAVIS_WORKER_PROVIDER_NAME: "gce"
  TRAVIS_WORKER_GCE_BOOT_POLL_SLEEP: "7s"
  TRAVIS_WORKER_GCE_BOOT_PRE_POLL_SLEEP: "5s"
  TRAVIS_WORKER_GCE_DISK_SIZE: "70"
  TRAVIS_WORKER_GCE_IMAGE_DEFAULT: "travis-ci-garnet-trusty.%2B"
  TRAVIS_WORKER_GCE_IMAGE_PROJECT_ID: "eco-emissary-99515"
  TRAVIS_WORKER_GCE_IMAGE_SELECTOR_TYPE: "api"
  TRAVIS_WORKER_GCE_MACHINE_TYPE: "n1-standard-1"
  TRAVIS_WORKER_GCE_PROJECT_ID: "travis-staging-1"
  TRAVIS_WORKER_GCE_PUBLIC_IP: "false"
  TRAVIS_WORKER_GCE_PUBLIC_IP_CONNECT: "false"
  TRAVIS_WORKER_GCE_RATE_LIMIT_DYNAMIC_CONFIG: "true"
  TRAVIS_WORKER_GCE_RATE_LIMIT_MAX_CALLS: "30"
  TRAVIS_WORKER_GCE_RATE_LIMIT_PREFIX: "worker"
  TRAVIS_WORKER_GCE_RATE_LIMIT_TICK: "2s"
  TRAVIS_WORKER_GCE_REGION: "us-central1"
  TRAVIS_WORKER_GCE_SKIP_STOP_POLL: "true"
  TRAVIS_WORKER_GCE_UPLOAD_RETRIES: "300"
  {{ if .Values.project -}}
  TRAVIS_WORKER_STACKDRIVER_PROJECT_ID: "{{ .Values.project }}"
  {{- end }}

  TRAVIS_WORKER_OPENCENSUS_SAMPLING_RATE: "10"
  TRAVIS_WORKER_OPENCENSUS_TRACING_ENABLED: "true"

  TRAVIS_WORKER_PPROF_PORT: "6060"
  GOTRACEBACK: "all"
